[package]
name = "factory-game"
version = "0.3.0"
edition = "2024"
resolver = "2"

[features]
default = ["invariant-check", "ui"]
ui = ["bevy/3d","bevy/bevy_color", "dep:rand"]
invariant-check = []
proptests = ["dep:proptest", "dep:rand"]
dev = ["bevy/bevy_dev_tools"]
debug = ["bevy/debug"]

[dependencies]
bevy = {version="0.18.0", default-features = false, features = ["bevy_log"]}
derivative = "2.2.0"
ron = "0.11"
serde = { version = "1.0", features = ["derive"] }

# Optional dev-dependencies
proptest = { version = "1.5.0", optional = true }
rand = { version = "0.8", optional = true }

[dev-dependencies]
pretty_assertions = "1.4.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
