[alias]
ts = "test --no-default-features --features=invariant-check"
tsp = "test --no-default-features --features=invariant-check,proptests"
release = "build --release --no-default-features --features=ui"
