[alias]
# Run the tests, with no UI
ts = "test --no-default-features --features=invariant-check --package factory-core"
# Run all tests
t = "test --workspace"
# Run the property based tests, with no UI
tsp = "run --no-default-features --package proptests"
release = "build --release --no-default-features --features=ui"
# Run the UI with no invariant checking
rni = "run --no-default-features --features=ui"
